### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by marksmeets** [deeplearning4j/rl4j#11]
These are the steps I took to get rl4j-examples to compile. Unfortunately it stops with a runtime error.

`mkdir work`
`cd work`
`git clone https://github.com/rubenfiszel/rl4j-examples.git`

Open rl4j-examples in intellij. The project will fail to build, because the pom references rl4j-core 0.5.0-snapshot. Same goes for rl4j-doom, rl4j-gym. Upon closer expection, it has dependencies like

```pom.xml
    <dependency>
      <groupId>org.deeplearning4j.rl4j</groupId>
      <artifactId>rl4j-core</artifactId>
      <version>0.5.0-SNAPSHOT</version>
    </dependency>
```
But, they don't exist. What does exist is this:
```pom.xml
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>rl4j-core</artifactId>
      <version>0.6.0</version>
    </dependency>
```
(note the change in groupId)

I made this change in the pom. Unfortunately, there are three compile time problems now:
```
work/rl4j-examples/src/main/java/org/deeplearning4j/rl4j/Cartpole.java
Error:(4, 41) java: package org.deeplearning4j.rl4j.gym.space does not exist
work/rl4j-examples/src/main/java/org/deeplearning4j/rl4j/AsyncNStepCartpole.java
Error:(3, 41) java: package org.deeplearning4j.rl4j.gym.space does not exist
work/rl4j-examples/src/main/java/org/deeplearning4j/rl4j/A3CCartpole.java
Error:(3, 41) java: package org.deeplearning4j.rl4j.gym.space does not exist
```
They can easily be fixed by editing those files: change this:
`import org.deeplearning4j.rl4j.gym.space.Box;`
to
`import org.deeplearning4j.rl4j.space.Box;`

Now the project compiles, but it doesn't run. It complains about a logger and the fact that we didn't specify an nd4j backend. To keep things simple, I'll use native (no gpu)  and add this to the pom:
```pom.xml
   <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>0.6.0</version>
    </dependency>
<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.6.2</version>
    </dependency>
```

This solves the problem with the logger, and the backend. Unfortunately it fails with this output:
```
415 [main] INFO org.nd4j.nativeblas.NativeOps - Number of threads used for NativeOps: 4
1427 [main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
1552 [main] INFO org.reflections.Reflections - Reflections took 103 ms to scan 10 urls, producing 121 keys and 415 values 
DQNFactoryStdDense.Configuration(numLayer=3, numHiddenNodes=16, learningRate=0.001, l2=0.01)
3570 [main] INFO org.reflections.Reflections - Reflections took 1942 ms to scan 119 urls, producing 8860 keys and 45642 values 
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedClass.construct(Ljava/lang/Class;Lcom/fasterxml/jackson/databind/AnnotationIntrospector;Lcom/fasterxml/jackson/databind/introspect/ClassIntrospector$MixInResolver;)Lcom/fasterxml/jackson/databind/introspect/AnnotatedClass;
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.registerSubtypes(NeuralNetConfiguration.java:361)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.configureMapper(NeuralNetConfiguration.java:341)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.initMapperYaml(NeuralNetConfiguration.java:304)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.<clinit>(NeuralNetConfiguration.java:297)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.build(NeuralNetConfiguration.java:958)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:216)
	at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense.buildDQN(DQNFactoryStdDense.java:66)
	at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense.buildDQN(DQNFactoryStdDense.java:20)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init>(QLearningDiscreteDense.java:25)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init>(QLearningDiscreteDense.java:29)
	at org.deeplearning4j.rl4j.Toy.simpleToy(Toy.java:88)
	at org.deeplearning4j.rl4j.Toy.main(Toy.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

(This is with the main class from Toy. Similar things happen with Cartpole etc)
Looking at the code I see it tries to call AnnotatedClass.construct with first parameter of type Class, but the version of construct that is provided needs a JavaType as first parameter.  I get AnnotedClass from jackson-databind:2.8.1

I'm stuck here. There's a variation to this procedure as well; if I get the latest rl4j sources, build and mvn install them, then I can use them in the rl4j-examples pom. At runtime it gives the same problem though.
Any help would be greatly appreciated!
Mark Smeets.

**Comment by ecthx** [comment]
Try this pom with your rl4j-examples:
[https://gist.github.com/ecthx/c8abc05a235808ee0bae4b27f8ba609b](url)

**Comment by marksmeets** [comment]
awesome, it gets past the error. It's not 100% good, after some training 
I get a new RuntimeException (connection error), but let me first look 
into that myself.

Thanks, this will help me a lot, no doubt!

Mark.
