### ISSUE TITLE
Failed to allocate memory within limits: totalBytes = 2G + 76M > maxBytes = 2G

### ISSUE THREAD

**Issue by Ceubex** [deeplearning4j/rl4j#26]
Hi,

I run a derivated of HardToy example and it works during sevral hundred of iteration but after 30 minutes I have the following error.
I thing there is something in the model wich accumulate data, but I want it do not accumulate too much (my works well after 1000 iterations and is stable, so it is ok for me)

Here my error :

`Exception in thread "Thread-40" java.lang.OutOfMemoryError: Cannot allocate new DoublePointer(10000000): totalBytes = 2G, physicalBytes = 4G
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:76)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:440)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:426)
	at org.nd4j.linalg.api.buffer.DoubleBuffer.<init>(DoubleBuffer.java:48)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createDouble(DefaultDataBufferFactory.java:223)
	at org.nd4j.rng.NativeRandom.<init>(NativeRandom.java:78)
	at org.nd4j.rng.NativeRandom.<init>(NativeRandom.java:67)
	at org.nd4j.rng.NativeRandom.<init>(NativeRandom.java:63)
	at org.nd4j.linalg.cpu.nativecpu.rng.CpuNativeRandom.<init>(CpuNativeRandom.java:14)
	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.nd4j.linalg.factory.RandomFactory.getRandom(RandomFactory.java:29)
	at org.nd4j.linalg.factory.Nd4j.getRandom(Nd4j.java:520)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:624)
	at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense.buildDQN(DQNFactoryStdDense.java:31)
	at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense.buildDQN(DQNFactoryStdDense.java:20)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init>(QLearningDiscreteDense.java:25)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init>(QLearningDiscreteDense.java:29)
	at main.LanceurAppreneur$1.run(Appreneur.java:169)
Caused by: java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 2G + 76M > maxBytes = 2G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:558)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.DoublePointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:68)
	... 20 more`

The working code :

`
    public static QLearning.QLConfiguration CONF_QL =
            new QLearning.QLConfiguration(
                    123,   //Random seed
                    100000,//Max step By epoch
                    80000, //Max step
                    10000, //Max size of experience replay
                    32,    //size of batches
                    100,   //target update (hard)
                    0,     //num step noop warmup
                    0.05,  //reward scaling
                    0.99,  //gamma
                    10.0,  //td-error clipping
                    0.1f,  //min epsilon
                    2000,  //num step for eps greedy anneal
                    true   //double DQN
            );

    public static DQNFactoryStdDense.Configuration CONF_NET =
            new DQNFactoryStdDense.Configuration(
                    3,        //number of layers
                    16,       //number of hidden nodes
                    0.001,    //learning rate
                    0.01      //l2 regularization
            );

    public void apprendre() {
    	new Thread() {

			@Override
    		public void run() {
    			
    			//record the training data in rl4j-data in a new folder
    	        manager = new DataManager();

    	        //define the mdp from market
    	        Appreneur mdp = new Appreneur();
    	        mdp.LanceurAppreneur=LanceurAppreneur.this;
    	        //Appreneur mdp = (Appreneur) Fc.lireO("appreneur.obj");
    	        appreneur=mdp;

    	        //define the training
    	        dql = new QLearningDiscreteDense(mdp, CONF_NET, CONF_QL, manager);

    	        //start the training
    	        dql.train();

    	        /*
    	        System.out.println(Fc.octets(manager));
    	        System.out.println(Fc.octets(mdp));
    	        System.out.println(Fc.octets(dql));
    	        */
    	        
    	        //useless on toy but good practice!
    	        mdp.close();
    		}
    	}.start();
    }`

**Comment by raver119** [comment]
Such exceptions have only 1 solution: set higher Xmx value.
