### ISSUE TITLE
Exception when using StatsListener with A3C

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#50]
I was able to enable UI after it was enabled in rl4j recently but after one of the recent updates I started getting this exception:

`Exception in thread "Thread-6" java.lang.NullPointerException
	at org.deeplearning4j.ui.stats.BaseStatsListener.iterationDone(BaseStatsListener.java:461)
	at org.deeplearning4j.rl4j.network.ac.ActorCriticSeparate.applyGradient(ActorCriticSeparate.java:109)
	at org.deeplearning4j.rl4j.learning.async.AsyncGlobal.run(AsyncGlobal.java:77)`

I also noticed that A3C performance is pretty bad ...

**Comment by saudet** [comment]
That just means you registered a `null` reference as listener: That's not going to work.

Could you elaborate on "pretty bad"?

**Comment by ecthx** [comment]
Did not have time to investigate whats going on. Just dont like how the training looks.
![screen](https://user-images.githubusercontent.com/16616179/28757941-48f5475a-7553-11e7-9b12-88b21efa0219.png)
