### ISSUE TITLE
VizDoom saved movies and model loading

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/rl4j#61]
#### Issue Description

I was able to get the VizDoom examples running on my Windows 7 machine. If I set render=true when setting up the VizDoom MDP, then I can see the NN playing the game as it learns. However, the mp4 videos that get saved in the rl4j-data subdirectory are all completely black. They open and play just fine, but they consist of a couple of seconds of a black screen. The code also saves networks to a model subdirectory, with names like 101.model. When I try loading one of these networks, it successfully loads the network and launches the game, but then crashes with the following exception: 

`Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Cannot do forward pass in Convolution layer (layer name = layer0, layer index = 0): input array depth does not match CNN layer configuration (data input depth = 600, [minibatch,inputDepth,height,width]=[1, 600, 800, 3]; expected input depth = 4)`

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc)
Windows 7 
VizDoom 1.1.0 (Java version pre-compiled from https://github.com/mwydmuch/ViZDoom/releases/tag/1.1.0)
Java 1.8.0_144

**Comment by saudet** [comment]
That should be fixed in 0.9.1, but there are other bugs in there with CNNs that were fixed since, so make sure to try 0.9.2-SNAPSHOT.

**Comment by schrum2** [comment]
So, I tried changing dl4j.version in my pom file to 0.9.2. This compiled and ran, but resulted in the same problems. However, I had left the other versions at 0.8.0.

So, the next thing I tried was to make all versions be 0.9.2:
nd4j.version
dl4j.version
datavec.version
arbiter.version
rl4j.version
This doesn't work because nd4j and rl4j don't have this version yet?

Ok, so I made nd4j and rl4j be 0.9.1 (rest are still 0.9.2). I had to add two extra parameters to my DQNFactoryStdConv.Configuration constructor (both null, as in the ALE example), but everything compiled.

So, I ran this for a while, and the first movie it produced actually showed the game. Great!

However, then I tried to load the first model file it produced, and got the same error:

`Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Cannot do forward pass in Convolution layer (layer name = layer0, layer index = 0): input array depth does not match CNN layer configuration (data input depth = 600, [minibatch,inputDepth,height,width]=[1, 600, 800, 3]; expected input depth = 4) (layer name: layer0, layer index: 0)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:294)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:248)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:392)
	at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:309)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:789)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:929)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:870)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:861)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.silentOutput(MultiLayerNetwork.java:1906)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:1898)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:1871)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:1952)
	at org.deeplearning4j.rl4j.network.dqn.DQN.output(DQN.java:49)
	at org.deeplearning4j.rl4j.policy.DQNPolicy.nextAction(DQNPolicy.java:32)
	at org.deeplearning4j.rl4j.policy.DQNPolicy.nextAction(DQNPolicy.java:18)
	at org.deeplearning4j.rl4j.policy.Policy.play(Policy.java:72)
	at org.deeplearning4j.rl4j.policy.Policy.play(Policy.java:27)
	at org.deeplearning4j.examples.rl4j.Doom.loadDoom(Doom.java:118)
	at org.deeplearning4j.examples.rl4j.Doom.main(Doom.java:81)`


So, partial success. Just to be clear, at this point my pom looks like this:
 
    
    
        
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        
        <nd4j.version>0.9.1</nd4j.version>
        <dl4j.version>0.9.2</dl4j.version>
        <datavec.version>0.9.2</datavec.version>
        <arbiter.version>0.9.2</arbiter.version>
        <rl4j.version>0.9.1</rl4j.version>

        <logback.version>1.1.7</logback.version>    
  

Also, the command I'm using to load the network model is
`DQNPolicy<VizDoom.GameScreen> dqn = DQNPolicy.load("C:\\Users\\schrum2\\rl4j-data\\1\\model\\141.model");`

While I'm asking for help, finding out the preferred way to reference the rl4j-data directory (instead of globally) would also be nice.

**Comment by saudet** [comment]
The rl4j-data directory isn't meant to be used by the program, it's basically a log. Do you get the same error when trying to load a model that way but that was saved as follows?
```
QLearningDiscrete.getPolicy().save("mymodel");
```

**Comment by schrum2** [comment]
I let the training run to the point where it executes
`dql.getPolicy().save("doom-end.model");`
and then loaded it with
`DQNPolicy<VizDoom.GameScreen> dqn = DQNPolicy.load("doom-end.model");`
and got the same error.

However, there are also model files saved during training automatically in the rl4j-data\1\model subdir, where 1 is replaced by a new unclaimed number on each run. I suspect these model files are saved the same way, though I don't know where that particular save command appears.

**Comment by schrum2** [comment]
I should probably also say that although the "doom-end.model" was saved, there was an error at the end of training. I don't think it negatively affected the save process, but perhaps there is something going on that I don't understand. The Exception must have been handled somewhere, because the save happens after the Exception, whose trace is below:

`23:19:49.260 [main] ERROR org.deeplearning4j.rl4j.learning.sync.SyncLearning - Training failed.
java.lang.NullPointerException: null
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:50)
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:38)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:45)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:52)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscrete.trainStep(QLearningDiscrete.java:159)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning.trainEpoch(QLearning.java:91)
	at org.deeplearning4j.rl4j.learning.sync.SyncLearning.train(SyncLearning.java:38)
	at org.deeplearning4j.examples.rl4j.Doom.doomLearn(Doom.java:102)
	at org.deeplearning4j.examples.rl4j.Doom.main(Doom.java:80)
java.lang.NullPointerException
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:50)
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:38)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:45)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:52)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscrete.trainStep(QLearningDiscrete.java:159)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning.trainEpoch(QLearning.java:91)
	at org.deeplearning4j.rl4j.learning.sync.SyncLearning.train(SyncLearning.java:38)
	at org.deeplearning4j.examples.rl4j.Doom.doomLearn(Doom.java:102)
	at org.deeplearning4j.examples.rl4j.Doom.main(Doom.java:80)
eyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=30.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\schrum2\rl4j-data\2/video/video-3966-341666.mp4':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yuv420p, 800x600, q=2-31, 400 kb/s, 15360 tbn
[libx264 @ 000000009c20cde0] frame I:1     Avg QP:26.82  size: 28683
[libx264 @ 000000009c20cde0] frame P:24    Avg QP:32.07  size:  4634
[libx264 @ 000000009c20cde0] frame B:57    Avg QP:34.85  size:  1037
[libx264 @ 000000009c20cde0] consecutive B-frames:  4.9%  4.9%  7.3% 82.9%
[libx264 @ 000000009c20cde0] mb I  I16..4:  1.6% 77.3% 21.2%
[libx264 @ 000000009c20cde0] mb P  I16..4:  0.8%  5.1%  1.2%  P16..4: 44.0%  4.6%  2.4%  0.0%  0.0%    skip:41.9%
[libx264 @ 000000009c20cde0] mb B  I16..4:  0.1%  0.2%  0.0%  B16..8: 31.2%  1.0%  0.1%  direct: 0.3%  skip:67.1%  L0:53.1% L1:46.7% BI: 0.2%
[libx264 @ 000000009c20cde0] 8x8 transform intra:72.7% inter:87.8%
[libx264 @ 000000009c20cde0] coded y,uvDC,uvAC intra: 69.6% 61.6% 33.8% inter: 5.8% 3.5% 0.5%
[libx264 @ 000000009c20cde0] i16 v,h,dc,p: 46% 33% 12%  9%
[libx264 @ 000000009c20cde0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 14% 23%  7%  8%  7%  9%  7%  8%
[libx264 @ 000000009c20cde0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 25% 17%  5%  5%  4%  6%  4%  4%
[libx264 @ 000000009c20cde0] i8c dc,h,v,p: 60% 15% 22%  3%
[libx264 @ 000000009c20cde0] Weighted P-Frames: Y:25.0% UV:25.0%
[libx264 @ 000000009c20cde0] ref P L0: 62.5% 15.8% 16.2%  3.7%  1.9%
[libx264 @ 000000009c20cde0] ref B L0: 88.6%  9.7%  1.6%
[libx264 @ 000000009c20cde0] ref B L1: 94.9%  5.1%
[libx264 @ 000000009c20cde0] kb/s:582.47`

**Comment by saudet** [comment]
I'm unable to reproduce this with the Doom example here:
https://github.com/rubenfiszel/rl4j-examples/blob/master/src/main/java/org/deeplearning4j/rl4j/Doom.java
Could you provide a means to reproduce this issue?

**Comment by schrum2** [comment]
Can you even get the Doom example you posted to run? I figured I'd try in order to see if simply starting fresh with your code would work, but it won't even build:

git clone https://github.com/rubenfiszel/rl4j-examples.git
cd rl4j-examples/
mvn install

This causes an error:

[ERROR] Failed to execute goal on project rl4j-examples: Could not resolve dependencies for project org.deeplearning4j.rl4j:rl4j-examples:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.deeplearning4j.rl4j:rl4j-core:jar:0.5.0-SNAPSHOT, org.deeplearning4j.rl4j:rl4j-doom:jar:0.5.0-SNAPSHOT, org.deeplearning4j.rl4j:rl4j-gym:jar:0.5.0-SNAPSHOT: Could not find artifact org.deeplearning4j.rl4j:rl4j-core:jar:0.5.0-SNAPSHOT -> [Help 1]

I tried fiddling with the pom a lot, but even after switching over to different dependency versions, the final result did not work. 

I think that working with a minimal example like this would be the easiest way for us to find a common solution. I feel like I actually had to do a lot of weird tweaking to get the Doom example to build/run in my own code.

I can tell you how to recreate the error with my code, if you want to go that route, since it is on GitHub:

https://github.com/schrum2/MM-NEAT

If you clone this project, and then run mvn install, you should be able run the DL4J code that I added to my project. The class for Doom is based off the one you posted:
https://github.com/schrum2/MM-NEAT/blob/master/src/main/java/org/deeplearning4j/examples/rl4j/Doom.java

The main method runs doomLearn(), but if you comment it out and uncomment loadDoom() then you can try to load a saved file, which is what causes the org.deeplearning4j.exception.DL4JInvalidInputException

If you can troubleshoot the error within my code, that would be great, but I'm also happy to try getting a simpler Doom example to work on my end, if you can point me to one that builds properly.

Thank you for all the help.

**Comment by saudet** [comment]
Thanks! I see, the issue isn't with the loading, but the playing.
