### ISSUE TITLE
A3C crash when pass in valueNet and PolicyNet

### ISSUE THREAD

**Issue by Ailanz** [deeplearning4j/rl4j#83]
#### Issue Description

Hi, When I pass in my own networks into valueNet and policyNet, it will crash during training.

Here is how I call it:

`A3CDiscreteDense<SingleCoinState> dql = new A3CDiscreteDense<>(mdp, new ActorCriticSeparate(getNetwork(in,1), getNetwork(in,3)), CARTPOLE_A3C, manager);`

getNetwork():

```
public static MultiLayerNetwork getNetwork(int in, int out){
        MultiLayerNetwork net = new MultiLayerNetwork(new NeuralNetConfiguration.Builder()
                .seed(123)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .learningRate(0.01)
                .weightInit(WeightInit.XAVIER)
                .updater(Updater.NESTEROVS)
                .list()
                .layer(0, new DenseLayer.Builder().nIn(in).nOut(2)
                        .activation(Activation.TANH)
                        .build())
                .layer(1, new OutputLayer.Builder(LossFunctions.LossFunction.MSE)
                        .activation(Activation.IDENTITY)
                        .nOut(out).build())
                .pretrain(false).backprop(true).build()
        );
        net.init();
        net.setListeners(new ScoreIterationListener(1));
        return net;
    }
```

After starting to train, it crashes when it tries to update the network:

```
java.lang.IndexOutOfBoundsException: -1
	at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:90)
	at org.bytedeco.javacpp.indexer.FloatRawIndexer.put(FloatRawIndexer.java:90)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.put(BaseDataBuffer.java:1080)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1343)
	at org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CThreadDiscrete.calcGradient(A3CThreadDiscrete.java:100)
	at org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CThreadDiscrete.calcGradient(A3CThreadDiscrete.java:28)
	at org.deeplearning4j.rl4j.learning.async.AsyncThreadDiscrete.trainSubEpoch(AsyncThreadDiscrete.java:123)
	at org.deeplearning4j.rl4j.learning.async.AsyncThread.run(AsyncThread.java:82)
```

Please describe your issue, along with:
- expected behavior
not fail
- encountered behavior
failed

#### Version Information
        <rl4j.version>0.9.1</rl4j.version>
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
What is "in"?

**Comment by Ailanz** [comment]
Sorry, to be more clear. This error happens when I pass in custom networks (valueNet and policyNet) 
`new ActorCriticSeparate(getNetwork(in,1), getNetwork(in,3))`

and the error happens when running it.

The error will not happen if I use the configuration builder instead:

```
    private static ActorCriticFactorySeparateStdDense.Configuration CARTPOLE_NET_A3C =  ActorCriticFactorySeparateStdDense.Configuration
            .builder().l2(0).numHiddenNodes(2).useLSTM(true).numLayer(2).build();
```

please assist.

Thanks!

**Comment by saudet** [comment]
I sort of get that, but please provide more information so I can understand/reproduce this. Could you at least provide the value of "in"?

**Comment by Ailanz** [comment]
Oh, the value of 'in' is 3

**Comment by saudet** [comment]
Ok, and what does mdp.getObservationSpace().getShape() and mdp.getActionSpace().getSize() return?

**Comment by Ailanz** [comment]
mdp.getObservationSpace().getShape() is 12 and mdp.getActionSpace().getSize() is 3

**Comment by saudet** [comment]
So, `in` should also be 12...

**Comment by Ailanz** [comment]
Hi, sorry I was looking at a different example.

I changed the code to:
int in = mdp.getObservationSpace().getShape()[0];
        A3CDiscreteDense<SingleCoinState> dql = new A3CDiscreteDense<>(mdp, new ActorCriticSeparate(getNetwork(in,1), getNetwork(in,3)), CARTPOLE_A3C, manager);

and the actionSpace is 3, this is still throwing the same error.

**Comment by saudet** [comment]
Ok, could you prepare an example that fails based on say A3CCartpole?

**Comment by andrewtu** [comment]
I modified SimpleToy to reproduce this. Please refer below.

Thanks!

```
package org.deeplearning4j.examples.rl4j;

import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.Updater;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CDiscrete;
import org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CDiscreteDense;
import org.deeplearning4j.rl4j.learning.async.nstep.discrete.AsyncNStepQLearningDiscrete;
import org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning;
import org.deeplearning4j.rl4j.mdp.toy.SimpleToy;
import org.deeplearning4j.rl4j.mdp.toy.SimpleToyState;
import org.deeplearning4j.rl4j.network.ac.ActorCriticSeparate;
import org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense;
import org.deeplearning4j.rl4j.util.DataManager;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.lossfunctions.LossFunctions;

import java.io.IOException;

/**
 * @author rubenfiszel (ruben.fiszel@epfl.ch) on 8/11/16.
 *
 * main example for toy DQN
 *
 */
public class Toy {


    public static QLearning.QLConfiguration TOY_QL =
            new QLearning.QLConfiguration(
                    123,   //Random seed
                    100000,//Max step By epoch
                    80000, //Max step
                    10000, //Max size of experience replay
                    32,    //size of batches
                    100,   //target update (hard)
                    0,     //num step noop warmup
                    0.05,  //reward scaling
                    0.99,  //gamma
                    10.0,  //td-error clipping
                    0.1f,  //min epsilon
                    2000,  //num step for eps greedy anneal
                    true   //double DQN
            );


    public static AsyncNStepQLearningDiscrete.AsyncNStepQLConfiguration TOY_ASYNC_QL =
            new AsyncNStepQLearningDiscrete.AsyncNStepQLConfiguration(
                    123,        //Random seed
                    100000,     //Max step By epoch
                    80000,      //Max step
                    8,          //Number of threads
                    5,          //t_max
                    100,        //target update (hard)
                    0,          //num step noop warmup
                    0.1,        //reward scaling
                    0.99,       //gamma
                    10.0,       //td-error clipping
                    0.1f,       //min epsilon
                    2000        //num step for eps greedy anneal
            );


    public static DQNFactoryStdDense.Configuration TOY_NET =
             DQNFactoryStdDense.Configuration.builder()
        .l2(0.01).learningRate(1e-2).numLayer(3).numHiddenNodes(16).build();

    public static void main(String[] args) throws IOException {
        simpleToy();

    }

    public static void simpleToy() throws IOException {
        DataManager manager = new DataManager();
        SimpleToy mdp = new SimpleToy(20);
        int in = mdp.getObservationSpace().getShape()[0];
        A3CDiscreteDense<SimpleToyState> dql = new A3CDiscreteDense<>(mdp, new ActorCriticSeparate(getNetwork(in,1), getNetwork(in,mdp.getActionSpace().getSize())), A3C_CONFIG, manager);
        dql.train();
        mdp.close();
    }

    private static A3CDiscrete.A3CConfiguration A3C_CONFIG =
        new A3CDiscrete.A3CConfiguration(
            123,            //Random seed
            800000,            //Max step By epoch
            50000,         //Max step
            12,              //Number of threads
            5000000,              //t_max
            0,             //num step noop warmup
            1,           //reward scaling
            0.99,           //gamma
            10           //td-error clipping
        );

    public static MultiLayerNetwork getNetwork(int in, int out){
        int i = 0;
        MultiLayerNetwork net = new MultiLayerNetwork(new NeuralNetConfiguration.Builder()
            .seed(123)
            .miniBatch(true)
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
            .learningRate(0.00025)
            .weightInit(WeightInit.XAVIER)
            .updater(Updater.RMSPROP)     //To configure: .updater(new Nesterovs(0.9))
            .list()
            .layer(i++, new DenseLayer.Builder().nIn(in).nOut(250)   //12 is standard
                .activation(Activation.RELU)
                .build())
            .layer(i++, new DenseLayer.Builder().nOut(250)   //12 is standard
                .activation(Activation.RELU)
                .build())

            .layer(i++, new OutputLayer.Builder(LossFunctions.LossFunction.MSE)
                .activation(Activation.IDENTITY)
                .nOut(out).build())
            .pretrain(false).backprop(true).build()
        );
        net.init();
        return net;
    }
}

```

**Comment by Ailanz** [comment]
I modified SimpleToy from rl4j example to reproduce this. Please refer below.

Thanks!

```
package org.deeplearning4j.examples.rl4j;

import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.Updater;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CDiscrete;
import org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CDiscreteDense;
import org.deeplearning4j.rl4j.mdp.toy.SimpleToy;
import org.deeplearning4j.rl4j.mdp.toy.SimpleToyState;
import org.deeplearning4j.rl4j.network.ac.ActorCriticSeparate;
import org.deeplearning4j.rl4j.util.DataManager;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.lossfunctions.LossFunctions;

import java.io.IOException;

/**
 * @author rubenfiszel (ruben.fiszel@epfl.ch) on 8/11/16.
 *
 * main example for toy DQN
 *
 */
public class Toy {

    public static void main(String[] args) throws IOException {
        simpleToy();
    }

    public static void simpleToy() throws IOException {
        DataManager manager = new DataManager();
        SimpleToy mdp = new SimpleToy(20);
        int in = mdp.getObservationSpace().getShape()[0];
        A3CDiscreteDense<SimpleToyState> dql = new A3CDiscreteDense<>(mdp, new ActorCriticSeparate(getNetwork(in,1), getNetwork(in,mdp.getActionSpace().getSize())), A3C_CONFIG, manager);
        dql.train();
        mdp.close();
    }

    private static A3CDiscrete.A3CConfiguration A3C_CONFIG =
        new A3CDiscrete.A3CConfiguration(
            123,            //Random seed
            800000,            //Max step By epoch
            50000,         //Max step
            12,              //Number of threads
            5000000,              //t_max
            0,             //num step noop warmup
            1,           //reward scaling
            0.99,           //gamma
            10           //td-error clipping
        );

    public static MultiLayerNetwork getNetwork(int in, int out){
        int i = 0;
        MultiLayerNetwork net = new MultiLayerNetwork(new NeuralNetConfiguration.Builder()
            .seed(123)
            .miniBatch(true)
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
            .learningRate(0.00025)
            .weightInit(WeightInit.XAVIER)
            .updater(Updater.RMSPROP)     //To configure: .updater(new Nesterovs(0.9))
            .list()
            .layer(i++, new DenseLayer.Builder().nIn(in).nOut(250)   //12 is standard
                .activation(Activation.RELU)
                .build())
            .layer(i++, new DenseLayer.Builder().nOut(250)   //12 is standard
                .activation(Activation.RELU)
                .build())

            .layer(i++, new OutputLayer.Builder(LossFunctions.LossFunction.MSE)
                .activation(Activation.IDENTITY)
                .nOut(out).build())
            .pretrain(false).backprop(true).build()
        );
        net.init();
        return net;
    }
}
```

**Comment by saudet** [comment]
I see what the issue is. The policy network must return a probability distribution (that is to say "softmax", which you are using). I've added a clear error message for these cases in the latest commit: https://github.com/deeplearning4j/rl4j/commit/123bb1d7b1ff8156745967304bd368d26104edc7
